#!/usr/bin/env python3
"""Write the virtual printer rig's Markdown report from the step results.

Inputs are the sliced G-code and the JSON results of the Klipper and Moonraker
steps; a step that did not run is reported as such. Exit status: 0 written,
2 usage.
"""

import argparse
import datetime
import json
import os
import re
import sys

READ_SIZE = 64 * 1024


def load_json(path):
    if path is None or not os.path.isfile(path):
        return None
    with open(path) as f:
        return json.load(f)


def gcode_facts(path):
    if path is None or not os.path.isfile(path):
        return None
    size = os.path.getsize(path)
    with open(path, "rb") as f:
        head = f.read(READ_SIZE).decode(errors="replace")
        f.seek(max(0, size - READ_SIZE))
        tail = f.read().decode(errors="replace")

    def find(pattern, text):
        match = re.search(pattern, text, re.MULTILINE)
        return match.group(1).strip() if match else None

    return {
        "size": size,
        "generator": find(r"^; generated by (.+?) on \d", head),
        "estimated_time": find(r"^; estimated printing time \(normal mode\) = (.+)$", tail),
        "first_layer_estimate": find(
            r"^; estimated first layer printing time \(normal mode\) = (.+)$", tail),
        "thumbnails_config": find(r"^; thumbnails = (.*)$", tail),
        "thumbnail_blocks": len(re.findall(r"^; thumbnail(?:_\w+)? begin", head, re.MULTILINE)),
        "defined_objects": re.findall(r"^EXCLUDE_OBJECT_DEFINE\s+NAME=(\S+)", head, re.MULTILINE),
    }


def dhms_to_seconds(text):
    if not text:
        return None
    total = 0.0
    for value, unit in re.findall(r"([\d.]+)\s*([dhms])", text):
        total += float(value) * {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
    return total


def fmt(value):
    return "n/a" if value is None else str(value)


def section_slice(lines, facts, args):
    lines.append("## 1. Slice (KLIPSLICE CLI)")
    lines.append("")
    if facts is None:
        lines.append("**Not run or no G-code produced.**")
        lines.append("")
        return
    lines += [
        "- Binary: `%s`" % args.binary,
        "- Model: `%s`" % args.model,
        "- Presets: %s" % args.presets,
        "- G-code: `%s` (%d bytes)" % (os.path.basename(args.gcode), facts["size"]),
        "- Header `generated by`: `%s`" % fmt(facts["generator"]),
        "- Slicer estimate: %s; \"first layer\" estimate in the header: %s"
        % (fmt(facts["estimated_time"]), fmt(facts["first_layer_estimate"])),
        "- Objects defined (EXCLUDE_OBJECT_DEFINE): %s"
        % (", ".join("`%s`" % o for o in facts["defined_objects"]) or "none"),
        "- Thumbnails configured: `%s`; thumbnail blocks in file: %d"
        % (fmt(facts["thumbnails_config"]), facts["thumbnail_blocks"]),
        "",
    ]


def section_klipper(lines, summary, facts):
    lines.append("## 2. Klipper batch mode")
    lines.append("")
    if summary is None:
        lines.append("**Not run.**")
        lines.append("")
        return
    lines.append("**Verdict: %s** (klippy exit code %s, %d commands processed)" % (
        "ACCEPTED" if summary["accepted"] else "REJECTED",
        summary["klippy_exit_code"], summary["commands_processed"]))
    lines.append("")
    for title, items in (("G-code errors", summary["gcode_errors"]),
                         ("Errors logged", summary["errors"]),
                         ("Warnings logged", summary["warnings"])):
        lines.append("- %s: %s" % (title, "none" if not items else ""))
        lines += ["  - `%s`" % i for i in items]
    unknown = summary["unknown_commands"]
    lines.append("- Unknown commands: %s" % (
        "none" if not unknown else ", ".join("`%s` x%d" % kv for kv in unknown.items())))
    deprecated = summary["deprecated_parameters"]
    lines.append("- Deprecated parameters (accepted, warning): %s" % ("none" if not deprecated else ""))
    lines += ["  - `%s %s=` x%d: %s" % (d["command"], d["param"], d["count"], d["note"])
              for d in deprecated]
    ignored = summary["ignored_parameters"]
    lines.append("- Parameters given but never read by Klipper (warning): %s"
                 % ("none" if not ignored else ""))
    lines += ["  - `%s`: %s" % (cmd, ", ".join("%s x%d" % kv for kv in params.items()))
              for cmd, params in ignored.items()]
    slicer_total = dhms_to_seconds(facts["estimated_time"]) if facts else None
    motion = summary["klipper_motion_time_s"]
    if motion is not None and slicer_total:
        lines.append("- Klipper motion time, first EXCLUDE_OBJECT_START to last flush: "
                     "%.1f s; slicer estimate %.0f s (%+.1f %%)"
                     % (motion, slicer_total, (slicer_total - motion) / motion * 100.0))
    else:
        lines.append("- Klipper motion time: %s" % fmt(motion))
    lines.append("- Klipper first-layer time (first to second EXCLUDE_OBJECT_START): %s s"
                 % fmt(summary["klipper_first_layer_time_s"]))
    lines.append("")
    lines.append("<details><summary>Command census</summary>")
    lines.append("")
    lines.append("| Command | Count | Parameters |")
    lines.append("|---|---:|---|")
    for cmd, entry in summary["command_census"].items():
        lines.append("| `%s` | %d | %s |" % (cmd, entry["count"],
                                            ", ".join(sorted(entry["params"])) or "-"))
    lines.append("")
    lines.append("</details>")
    lines.append("")


def section_moonraker(lines, result):
    lines.append("## 3. Moonraker")
    lines.append("")
    if result is None:
        lines.append("**Not run.**")
        lines.append("")
        return
    lines.append("**Verdict: %s**" % ("PASS" if result["passed"] else "FAIL"))
    lines += ["- FAIL: %s" % f for f in result["failures"]]
    lines.append("")
    r = result["responses"]
    info = r.get("server_info", {})
    pinfo = r.get("printer_info", {})
    lines.append("- Moonraker `%s`, Klipper `%s`, klippy_state `%s`" % (
        fmt(info.get("moonraker_version")), fmt(pinfo.get("software_version")),
        fmt(info.get("klippy_state"))))
    upload = r.get("upload", {})
    if upload:
        lines.append("- Upload: action `%s`, item `%s`" % (
            fmt(upload.get("action")), fmt(upload.get("item", {}).get("path"))))
    meta = r.get("metadata")
    if meta:
        lines.append("- `/server/files/metadata`:")
        for key in ("slicer", "slicer_version", "estimated_time", "layer_count",
                    "object_height", "layer_height", "first_layer_height",
                    "nozzle_diameter", "filament_name", "filament_type",
                    "filament_total", "filament_weight_total", "first_layer_extr_temp",
                    "first_layer_bed_temp", "printer_model", "mmu_print"):
            lines.append("  - `%s`: `%s`" % (key, fmt(meta.get(key))))
        thumbs = meta.get("thumbnails")
        lines.append("  - `thumbnails`: %s" % (
            "none" if not thumbs else ", ".join("%sx%s" % (t["width"], t["height"]) for t in thumbs)))
    objects = r.get("exclude_object")
    if objects is not None:
        lines.append("- `exclude_object.objects` during the print: %s" % (
            ", ".join("`%s`" % o["name"] for o in objects["objects"]) or "none"))
    end = r.get("print_end")
    if end:
        ps = end["print_stats"]
        lines.append("- `print_stats` at the end: state `%s`, message `%s`, info `%s`" % (
            ps["state"], ps.get("message", ""), json.dumps(ps.get("info"))))
    if "gcode_store_during_print" in r:
        bad = [e["message"] for e in r["gcode_store_during_print"]
               if e.get("message", "").startswith("!!") or "Unknown command" in e.get("message", "")]
        lines.append("- G-code errors/unknown commands reported during the print: %s"
                     % ("none" if not bad else "; ".join("`%s`" % b for b in bad)))
    hist = r.get("history_last", {}).get("jobs")
    if hist:
        lines.append("- History: job `%s` status `%s`" % (hist[0]["job_id"], hist[0]["status"]))
    if "configfile_warnings" in r:
        lines.append("- Klipper config warnings: %s" % (
            "none" if not r["configfile_warnings"] else json.dumps(r["configfile_warnings"])))
    lines.append("")
    lines.append("Full API responses: `moonraker.json`.")
    lines.append("")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--gcode", required=True)
    parser.add_argument("--binary", required=True)
    parser.add_argument("--model", required=True)
    parser.add_argument("--presets", required=True)
    parser.add_argument("--klipper", required=True)
    parser.add_argument("--moonraker", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    facts = gcode_facts(args.gcode)
    klipper = load_json(args.klipper)
    moonraker = load_json(args.moonraker)
    ok = (facts is not None and klipper is not None and klipper["accepted"]
          and moonraker is not None and moonraker["passed"])
    lines = [
        "# KLIPSLICE virtual printer report",
        "",
        "Generated %s UTC. Overall: **%s**" % (
            datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
            "PASS" if ok else "FAIL"),
        "",
    ]
    section_slice(lines, facts, args)
    section_klipper(lines, klipper, facts)
    section_moonraker(lines, moonraker)
    with open(args.out, "w") as f:
        f.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
